name: nfc_multi_read_in_flutter
description: Flutter plugin to write NFC tags on both Android and iOS. Currently it only supports reading NDEF formatted tags.
version: 2.0.5
homepage: https://github.com/zippyrainbow/nfc_multi_read_in_flutter
repository: https://github.com/zippyrainbow/nfc_multi_read_in_flutter

environment:
    sdk: ">=2.1.0 <3.0.0"
    flutter: ">=1.10.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
        platforms:
            android:
                package: me.andisemler.nfc_multi_read_in_flutter
                pluginClass: NfcWriteInFlutterPlugin
            ios:
                pluginClass: NfcWriteInFlutterPlugin

