name: Build example app

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download Flutter
      run: curl -o flutter_linux_v1.12.13+hotfix.9-stable.tar.xz https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.9-stable.tar.xz
    - name: Unpack Flutter
      run: tar xf flutter_linux_v1.12.13+hotfix.9-stable.tar.xz
    - name: Run Flutter doctor
      run: ./flutter/bin/flutter doctor
    - name: Build example/
      run: cd example && ../flutter/bin/flutter build appbundle
  build-ios:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Download Flutter
      run: curl -o flutter_macos_v1.12.13+hotfix.9-stable.zip https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.12.13+hotfix.9-stable.zip
    - name: Unpack Flutter
      run: unzip flutter_macos_v1.12.13+hotfix.9-stable.zip
    - name: Run Flutter doctor
      run: ./flutter/bin/flutter doctor
    - name: Build example/
      run: cd example && ../flutter/bin/flutter build ios --no-codesign
      timeout-minutes: 10
